"""Initial Schema

Revision ID: 6de7bed489bf
Revises: 
Create Date: 2024-01-22 18:30:33.752330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6de7bed489bf"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "property_ads",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("neighboorhood", sa.String(length=64), nullable=True),
        sa.Column("city", sa.String(length=64), nullable=True),
        sa.Column(
            "listing_purpose",
            sa.Enum("rental", "purchase", "both", name="listingpurpose"),
            nullable=False,
        ),
        sa.Column("uf", sa.String(length=2), nullable=True),
        sa.Column(
            "mustHaveItems", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "desiredItems", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("min_budget", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("max_budget", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("term_acceptance", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("property_ads")
    # ### end Alembic commands ###
